# Generated by Django 3.1.4 on 2021-01-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(default='/media/image/temple.png', upload_to='product/images/'),
        ),
    ]
