# Generated by Django 3.1.4 on 2021-01-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0002_auto_20210109_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='first_image',
            field=models.ImageField(height_field='img_height', upload_to='banner/image/', width_field='img_width'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='long_banner_image',
            field=models.ImageField(height_field='img_height', upload_to='banner/image/', width_field='img_width'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='second_image',
            field=models.ImageField(height_field='img_height', upload_to='banner/image/', width_field='img_width'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='third_image',
            field=models.ImageField(height_field='img_height', upload_to='banner/image/', width_field='img_width'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='banner_four',
            field=models.ImageField(upload_to='banner/image/'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='banner_one',
            field=models.ImageField(upload_to='banner/image/'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='banner_three',
            field=models.ImageField(upload_to='banner/image/'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='banner_two',
            field=models.ImageField(upload_to='banner/image/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ManyToManyField(blank=True, to='color.ThemeCategory', verbose_name='product_theme_category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_frame_size',
            field=models.ManyToManyField(blank=True, to='color.FrameSize', verbose_name='product_frame_size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(default='/media/image/temple.png', upload_to='product/image/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_page_size',
            field=models.ManyToManyField(blank=True, to='color.PageSize', verbose_name='product_page_size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_related_to_gender',
            field=models.ManyToManyField(blank=True, to='color.Gender', verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.ManyToManyField(blank=True, to='color.ProductSize', verbose_name='product_size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_theme',
            field=models.ManyToManyField(blank=True, to='color.Theme', verbose_name='product_theme'),
        ),
    ]
