# Generated by Django 3.1.4 on 2021-01-12 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0003_auto_20210111_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ManyToManyField(blank=True, to='color.ThemeCategory', verbose_name='Product Theme Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_frame_size',
            field=models.ManyToManyField(blank=True, to='color.FrameSize', verbose_name='Product Frame Size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_page_size',
            field=models.ManyToManyField(blank=True, to='color.PageSize', verbose_name='Product Page Size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_related_to_gender',
            field=models.ManyToManyField(blank=True, to='color.Gender', verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.ManyToManyField(blank=True, to='color.ProductSize', verbose_name='Product Size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_theme',
            field=models.ManyToManyField(blank=True, to='color.Theme', verbose_name='Product Theme'),
        ),
    ]
