# Generated by Django 3.1.4 on 2021-01-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0004_auto_20210112_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'COlor',
                'verbose_name_plural': 'COlors',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_color',
            field=models.ManyToManyField(to='color.Color', verbose_name='Add Hex code only for product'),
        ),
    ]
