# Generated by Django 3.1.4 on 2021-01-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0006_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='theme_image',
            field=models.FileField(default='/media/image/temple.png', upload_to='product/image/'),
        ),
        migrations.AddField(
            model_name='themecategory',
            name='category_image',
            field=models.FileField(default='/media/image/temple.png', upload_to='product/image/'),
        ),
    ]
