# Generated by Django 3.1.4 on 2021-01-23 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0009_auto_20210121_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_creator',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '1234567890'. Up to 10 digits allowed.", regex='^\\d{10,10}$')]),
        ),
    ]
