# Generated by Django 3.1.4 on 2021-01-23 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0010_auto_20210123_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('design_description', models.TextField()),
                ('design_image', models.ImageField(upload_to='product/image/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator User')),
            ],
            options={
                'verbose_name': 'CreatorDesign',
                'verbose_name_plural': 'CreatorDesigns',
            },
        ),
    ]
