# Generated by Django 3.1.4 on 2021-01-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0011_creatordesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatordesign',
            name='design_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
