# Generated by Django 3.1.4 on 2021-01-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0013_creatordesign_design_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='PUBG Grey T-shirt', max_length=100),
        ),
        migrations.AlterField(
            model_name='creatordesign',
            name='design_status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='under_review', max_length=50),
        ),
    ]
