# Generated by Django 3.1.4 on 2021-02-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0014_auto_20210124_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_creator',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
