# Generated by Django 3.1.4 on 2021-02-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0016_auto_20210216_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_creator',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
