# Generated by Django 3.1.4 on 2021-04-23 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0021_auto_20210421_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('review', models.CharField(help_text='Keep the review short and concise', max_length=150, verbose_name='Add your Review')),
                ('rating', models.PositiveIntegerField()),
                ('review_for_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='color.product', verbose_name='Product Id')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User who reviewed Product')),
            ],
            options={
                'verbose_name': 'Reviews',
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
